---
title: Nix
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Debian, Ubuntu and macOS Guides
description: Formally the "Debian Wiki" this is a refreshed collection of *nix based
  howto's that I've created over the years for Linux and macOS specifically for Debian,
  Ubuntu and Mac OS X.
avatar: https://avatars2.githubusercontent.com/u/717118?v=3&s=460
footer-links:
  dribbble: 
  email: justin@hartman.me
  facebook: 
  flickr: 
  github: justinhartman/nix
  instagram: 
  linkedin: justinhartman
  pinterest: 
  rss: 
  twitter: justinhartman
  stackoverflow: 
  youtube: 
  googleplus: 
disqus: iamjustinhartman
google_analytics: 
url: https://justinhartman.github.io
baseurl: "/nix"
permalink: "/:title/"
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
gems:
- jekyll-sitemap
exclude:
- Gemfile
- Gemfile.lock
- README.md
- CNAME
- nix.sublime-project
- nix.sublime-workspace
